### ISSUE TITLE
Spanish translation suggestion

### ISSUE THREAD

**Issue by franhida** [dmuy/duDatepicker#11]
The translation for the '**Clear**' button should be 'Vaciar' or 'Limpiar' instead of 'Despejar' which does not apply in this context.
The most accurate would be 'Vaciar' although you can use any of both suggestions.
Good day.

**Comment by dmuy** [comment]
Deployed on commit https://github.com/dmuy/duDatepicker/commit/2f6dd7c5d4d33c7a43d9a4e83c65beed433f123e
