### ISSUE TITLE
Disable or select half day

### ISSUE THREAD

**Issue by logan-19** [dmuy/duDatepicker#14]
Hi, how can I disable half day or select half day, eg. for hotel booking?
Thanks!

eg.
![2](https://user-images.githubusercontent.com/28824929/103432991-54f50280-4be1-11eb-885b-a5d4d1df4a1b.PNG)

**Comment by dmuy** [comment]
Hi @logan-19,

Sorry for the very late reply. This feature is not available on this plugin. I think this feature involves time or is for display purposes only, so I think I won't be implementing this one.
