### ISSUE TITLE
Using inline inside jquery UI

### ISSUE THREAD

**Issue by quim831** [dmuy/duDatepicker#22]
Hello

I need to use the inline feature but inside a Modal Form from jQuery UI.
I think it's easy to check. This is the link from jQuery UI where you can just add duDatpicker to the popup "Create New User".
https://jqueryui.com/dialog/#modal-form

Outside the popup the inline feature works fine.
This is the code for duDatepicker:
` duDatepicker('#dt1,#dt2', {
                auto: true,          
                inline: true,
                format: 'yyyy-mm-dd', //range: true,               
                // Determines if Clear button is displayed
                clearBtn: true,
                // Determines if Cancel button is displayed
                cancelBtn: true,
                // Determines if clicking the overlay will close the date picker
                overlayClose: true,                  
            });`

This is the screenshot where I just add #dt1 (works fine) outside the popup and #dt2 (doesn't display the calendar) inside the popup:

![SharedScreenshot_10](https://user-images.githubusercontent.com/6391220/114560835-f2da7d80-9c64-11eb-9508-23d559e731d6.jpg)

Regards

**Comment by quim831** [comment]
Just dig a bit with Dialog from from jQuery UI and it seams the issue is related with a modal option from this component.

 diag1 = $("#dialog-form").dialog({
                autoOpen: false,
                height: 200,
                width: 250,
                closeOnEscape: true,
                modal: true //If False duDatepicker works fine               
            });

The situation is that I need to keep this popup modal to avoid any interference from to user to anything else than the popup.

**Comment by quim831** [comment]
Posting questions force us to dig for answers and with some workarounds it's possible do close the pop-up if the user clicks or do some actions outside the popup. This could not answer all the scenarios but it's a workaround in case we have to deal with this modal feature from jQuery UI.

**Comment by dmuy** [comment]
Hi @quim831,

I've tested this scenario and I think jquery UI has some code which prevents other DOM elements to be hidden (I'm not sure where exactly), and came to this solution:
```javascript
duDatepicker('#datepicker', { auto: true, inline: true, format: 'yyyy-mm-dd', root: '#dialog-form' });
```
Notice the configuration `root`. It places the datepicker DOM on the dialog itself, and became visible. You can see the [fiddle here](https://jsfiddle.net/4b0pxgs6/1/).

**Comment by quim831** [comment]
It made all the difference in did and the popup it's still modal. Thank you so much.
It's not easy to get a functional calendar with all these features and you have done a great work with duDatepicker.

Best Regards
