### ISSUE TITLE
Reset range when selecting new date

### ISSUE THREAD

**Issue by IanLuan** [dmuy/duDatepicker#29]
Is there an option to reset the range when the user selects a date after already having two dates selected? Currently it changes one of the two dates of the range (the closest), but I would like to reset it. Thank you!

**Comment by dmuy** [comment]
Hi @IanLuan,

What do you mean by reset? Like clearing the selection or no selection? If this is what you mean, there's no option for this.

**Comment by dmuy** [comment]
Closing as inactive (needs more info).
