### ISSUE TITLE
Date range format

### ISSUE THREAD

**Issue by revealitmedia** [dmuy/duDatepicker#3]
When setting up a date range with two inputs, if I try to format both fields as follows, I get an error:

$("#datefrom").duDatepicker({format: "mmmm dd, yyyy"});
$("#dateto").duDatepicker({format: "mmmm dd, yyyy"});

The error occurs on click and says: duDatepicker.js:559 Uncaught TypeError: Cannot read property 'length' of undefined

If I remove the formatting option on the $dateto field, it works as expected.

**Comment by revealitmedia** [comment]
Narrowed the problem down to the "mmmm" part, changing this fixes the problem, but doesnt show the full month as I want

**Comment by dmuy** [comment]
Hi @revealitmedia, sorry for this very late reply. I've checked the formatting, there's no problem with it. Can you comment how you coded the input elements?

**Comment by dmuy** [comment]
Hi @revealitmedia, I think I've recreated your problem. The error seems to occur if the value of the input is empty.

I've published the fix for this one on my latest commit.

Thanks
