### ISSUE TITLE
setMinDate and setMaxDate as built-in methods

### ISSUE THREAD

**Issue by cadeyrn** [dmuy/duDatepicker#32]
Hi,

I am considering this datepicker as a replacement for another one in an existing project, because a) it's more intuitively in your date picker to change the year and b) it looks much better than the currently used date picker. But to do so it's important that I can change the minDate and the maxDate properties at runtime, similar to the setValue built-in method that already exists.

Is that a feature you would consider to implement in your date picker?

**Comment by dmuy** [comment]
Implemented on 04f159395a12d666ae0162e3e7b1ee85e029f5c1, will be included on the next version release.

**Comment by Janith-Umeda** [comment]
Thanks :raised_hands:
