### ISSUE TITLE
Make the year range for _getYears() configurable

### ISSUE THREAD

**Issue by cadeyrn** [dmuy/duDatepicker#33]
In your _getYears() method you defines the following values:

_minYear = _.viewYear - 50,
_maxYear = _.viewYear + 25,

Would it possible to make these values configurable?

Use case: Among other use cases, i would also like to use the date picker as a picker for the birth date. The current year minus 50 years are not enough and I fear that the users don't understand that they can click again on the year to get other years for selection. So I would like to change the value for the MinYear to something like _.viewYear - 100.

**Comment by dmuy** [comment]
Implemented on 04f159395a12d666ae0162e3e7b1ee85e029f5c1, will be included on the next version release.
