### ISSUE TITLE
_getYears() should consider minDate and maxDate

### ISSUE THREAD

**Issue by cadeyrn** [dmuy/duDatepicker#34]
Hi!

I saw that you have already implemented my last feature requests, thanks for that! After this goes so well, I have directly the next suggestion. 😊

Could you consider the `minDate` and the `maxDate` in your `_getYears()` method?

Let's say you have a `maxDate` of 12/23/2022. Then 2022 should be the last year you get if you click on the year in the date picker, even if `laterYears` has a much larger value since you can't select any date in 2023 or later anyway.

**Comment by dmuy** [comment]
Hi @cadeyrn,

I have actually considered this when implementing the `minYear` and `maxYear` configurations. But I'd also have to implement a lot of value checking when the input already has a value or when the user sets a value (in all modes: single, multiple, date range), so I put it off for now, I'll add this in the future maybe.
