### ISSUE TITLE
Multiple dates not work as spected

### ISSUE THREAD

**Issue by Isilnar** [dmuy/duDatepicker#39]
duDatepicker version: 2.0.2

Code:
duDatepicker('#daterangemultiple', {multiple: true, i18n: 'es', format: 'dd/mm/yyyy'});
...
tmp_values = ["01/05/2022", "02/05/2022"];
...
duDatepicker('#daterangemultiple', 'setValue', tmp_values);
duDatepicker('#daterangemultiple', 'show');

Description:
I try to describe the issue, sorry for my english.
Open duDatepicker, if you click in some dates and push OK button, all works (show from console output):
{
    "isTrusted": false,
    "data": {
        "_dates": [
            "2022-05-19T22:00:00.000Z",
            "2022-05-25T22:00:00.000Z",
            "2022-05-27T22:00:00.000Z"
        ],
        "dates": [
            "20/05/2022",
            "26/05/2022",
            "28/05/2022"
        ]
    }
}

The issue happens when you stablish some dates in JS, open duDatepicker and click OK button without clicking more dates, JS stablish dates appears selected in duDatepicker, but in this case not work, console show:
{
    "isTrusted": false,
    "data": {
        "_dates": [],
        "dates": []
    }
}

Images:
First time open duDatepicker and click some dates, push OK and receive dates selected:
![image](https://user-images.githubusercontent.com/12487191/170227979-a7ac6bd3-94a7-46db-a25e-d469dd6e81e0.png)
![image](https://user-images.githubusercontent.com/12487191/170229440-78c5f716-d364-4dc6-9222-4f80c2520a23.png)

Then, you in your JS stablish previous selected dates and show:
tmp_values = ["20/05/2022","26/05/2022","28/05/2022"]
duDatepicker('#daterangemultiple', 'setValue', tmp_values);
duDatepicker('#daterangemultiple', 'show');

duDatepicker apears with previous dates marked:
![image](https://user-images.githubusercontent.com/12487191/170228918-44fe39e8-388e-481d-8c19-b31047a4b9ab.png)

But when you push OK button no dates are returned:
![image](https://user-images.githubusercontent.com/12487191/170229135-b69e5737-212c-499d-a999-92ca97056f8b.png)

**Comment by dmuy** [comment]
Hi @Isilnar,

I sort of understand what you mean. But I'm sorry to tell you that I can't seem to replicate this problem.

This is what I've tried:
```javascript
tmp_values = ['06/01/2021','07/01/2021']
duDatepicker('#multipicker', {
  theme: 'blue', multiple: true, format: 'mm/dd/yyyy',
    events: {
      dateChanged: function(data) {
        console.log('multipicker.dateChanged', data)
      }
    }
})
duDatepicker('#multipicker', 'setValue', tmp_values)
duDatepicker('#multipicker', 'show')
```

And this is the result after clicking OK:
![image](https://user-images.githubusercontent.com/8830886/172033872-78a6537c-9cfe-4559-982c-28ca4306227e.png)

So, I'm not sure what the problem is on your end.
