### ISSUE TITLE
Date changed event not firing on 'body' 

### ISSUE THREAD

**Issue by dev-santosh** [dmuy/duDatepicker#40]
Why am I not able to listen to "date changed" event using $('body').on('date changed,'element',....{})??
This should be possible, right?
]

**Comment by dmuy** [comment]
Hi @dev-santosh

I think this is not working currently because I didn't set the event bubbling to `true`. But thanks for pointing this out, I'll look into this when I update the event triggering code I used coz it's now deprecated.

**Comment by dev-santosh** [comment]
Really appreciated.
Currently, I have made few changes and using it via local copy/
