### ISSUE TITLE
How can i make it like the last two pictures

### ISSUE THREAD

**Issue by yobome** [dmuy/duDatepicker#6]
I wanna use the datepicker without the header (the blue or dark theme).
What should I do?
:)

**Comment by dmuy** [comment]
You have to add `inline: true` in the initialization configuration.

**Comment by yobome** [comment]
> You have to add `inline: true` in the initialization [configuration](https://github.com/dmuy/duDatepicker#using-configuration). To modify the theme see [here](https://github.com/dmuy/duDatepicker#themes)

Actually I meant that I don't want the upper part(the blue or dark part). Should I custom modify the theme? or is there a function?

**Comment by dmuy** [comment]
I see, you want the normal date picker (dialog) but without the header. There is no option or configuration for that, but if you really don't want to display the header you can just override the css

```css
.dudp__calendar-header {
    display: none !important;
}
```
