### ISSUE TITLE
Request : internationalization

### ISSUE THREAD

**Issue by badulesia** [dmuy/duDatepicker#7]
Hello.
Very good script, nice and effective. Nevertheless it's missing a key feature : internationalization.
Browsing the code I found very easily how to change the language but this is not a convinient way to do it.
What about an option giving an array for the day of the week ? Or an external file ?
Also is missing the possibility to change the first day of the week. In many countries it's monday and not sunday.
Can you think about these ?
thx.

**Comment by dmuy** [comment]
Implemented in this comment: https://github.com/dmuy/duDatepicker/commit/687018a11fd52e10995cc8fc1618d536cc48621e

**Comment by badulesia** [comment]
A very fast and effective answer ! Glad you added this. I have tested a lot (a lot !) of calendar scripts, but so far yours is the nicest. It only missed the i18n. I'm going testing ...
Thank you.

**Comment by dmuy** [comment]
Thanks! Glad to hear others appreciate my little project, it means a lot. 

Also, the button texts (even the other labels) in the preset i18n need improvement as I don't know much about other languages, and I don't know the right term to use for them.

**Comment by badulesia** [comment]
I have implemented you script, it was easy. I needed only a couple of tests to find the correct options and values. It works just fine.
The use of day/month names was the main goal I think. You've done a nice job in a short time indeed.
No one can blame you for not knowing extra vocabulary for ten languages ! :) It is the job of external contributors to help you in that case.  Maybe you can copy translations from another script/plugin that already use many languages.

For french
btnCancel: 'Abandonner',
btnClear: 'Effacer'

Thank you.
