### ISSUE TITLE
request : option for DOM parent node

### ISSUE THREAD

**Issue by badulesia** [dmuy/duDatepicker#8]
Hello.
By default, a calendar is appended to the body element. Is it possible to add an option to define a DOM parent node?
I would like the calendar to be appended to another DOM node rather than body.
Actually I have managed a small code that move the calendars DOM element to another parent node after the calendars are built. It would be more simple to append directly to the target node parent directly within your code.

#953
`hf.appendTo(picker.container, document.body);`
and a few other lines including 'document.body'.

**Comment by dmuy** [comment]
Implemented on this commit: https://github.com/dmuy/duDatepicker/commit/8671736e6d8076f88ec1fe1f310251f39d5871e2
