### ISSUE TITLE
Start date

### ISSUE THREAD

**Issue by stifboy** [dmuy/duDatepicker#9]
Is there a way to add a start date or when the dates or calendar should start showing?

**Comment by dmuy** [comment]
You mean, like when the date picker opens it shows the specific month of a start date?

**Comment by stifboy** [comment]
> You mean, like when the date picker opens it shows the specific month of a start date?

yes

**Comment by dmuy** [comment]
I see.

Currently there is no configuration on that. But, if there is no value (on the input) it will show the current date's month, otherwise it will show the selected date's month.

**Comment by dmuy** [comment]
> yes. Like when the date picker opens, it should show dates from October 2015 and below

What you can do is set the default value to October 31, 2015 and set the maxDate to `today`. ([read more](https://github.com/dmuy/duDatepicker/wiki/Usage#min-and-max))

**Comment by stifboy** [comment]
> > yes. Like when the date picker opens, it should show dates from October 2015 and below
> 
> What you can do is set the default `value` and `maxDate` to October 31, 2015. ([read more](https://github.com/dmuy/duDatepicker/wiki/Usage#min-and-max))

Can I set the default value without adding it to the input field?

**Comment by dmuy** [comment]
Yes. By specifying the `value` configuration upon initialization
```javascript
// default `format` config
duDatepicker('#datepicker', { value: '10/31/2015' });

// custom `format` config
duDatepicker('#datepicker', { format: 'yyyy-mm-dd', value: '2015-10-31' });
```
or calling `setValue` (after initialization)
```javascript
duDatepicker('#datepicker', 'setValue', '10/31/2015');
```
